---
title: "Myndir"
author: "Valtýr Sigurðsson"
date: '2022-06-23'
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(plyr)
library(ggtextures)
library(magick)

Sys.setlocale("LC_ALL", "Icelandic")
sysfonts::font_add_google("Catamaran", "Catamaran")
showtext::showtext_auto()
gogn <- readr::read_csv("https://raw.githubusercontent.com/harkanatta/skogar22/main/gogn/snid.csv", locale = locale("is",encoding = "latin1"))
fuglar <- structure(list(isl_heiti = c("Bjartmáfur", "Dvergmáfur", "Fjallkjói", 
                                "Fjöruspói", "Geirfugl", "Haftyrðill", "Heiðlóa", "Hettumáfur", 
                                "Hrossagaukur", "Hvítmáfur", "Jaðrakan", "Kjói", "Kría", "Langvía", 
                                "Lundi", "Lóuþræll", "Rauðbrystingur", "Rita", "Sanderla", "Sandlóa", 
                                "Sendlingur", "Silfurmáfur", "Skógarsnípa", "Skúmur", "Spói", 
                                "Stelkur", "Stormmáfur", "Stuttnefja", "Svartbakur", "Sílamáfur", 
                                "Teista", "Tildra", "Tjaldur", "Álka", "Óðinshani", "Þórshani", 
                                "Blesgæs", "Brandönd", "Duggönd", "Gargönd", "Grafönd", "Grágæs", 
                                "Gulönd", "Heiðagæs", "Helsingi", "Hrafnsönd", "Hávella", "Húsönd", 
                                "Margæs", "Rauðhöfðaönd", "Skeiðönd", "Skúfönd", "Stokkönd", 
                                "Straumönd", "Toppönd", "Urtönd", "Álft", "Æðarkóngur", "Æður", 
                                "Bjargdúfa", "Fálki", "Haförn", "Smyrill", "Rjúpa", "Auðnutittlingur", 
                                "Barrfinka", "Glókollur", "Gráspör", "Gráþröstur", "Hrafn", "Krossnefur", 
                                "Maríuerla", "Músarrindill", "Skógarþröstur", "Snjótittlingur", 
                                "Stari", "Steindepill", "Svartþröstur", "Þúfutittlingur", "Dílaskarfur", 
                                "Flórgoði", "Fýll", "Himbrimi", "Lómur", "Sjósvala", "Skrofa", 
                                "Stormsvala", "Súla", "Toppskarfur", "Keldusvín", "Brandugla", 
                                "Eyrugla", "Snæugla"), latn_heiti = c("Larus glaucoides", "Hydrocoloeus minutus", 
                                                              "Stercorarius longicaudus", "Numenius arquata", "Pinguinus impennis", 
                                                              "Alle alle", "Pluvialis apricaria", "Chroicocephalus ridibundus", 
                                                              "Gallinago gallinago", "Larus hyperboreus", "Limosa limosa", 
                                                              "Stercorarius parasiticus", "Sterna paradisaea", "Uria aalge", 
                                                              "Fratercula arctica", "Calidris alpina", "Calidris canutus", 
                                                              "Rissa tridactyla", "Calidris alba", "Charadrius hiaticula", 
                                                              "Calidris maritima", "Larus argentatus", "Scolopax rusticola", 
                                                              "Catharacta skua", "Numenius phaeopus", "Tringa totanus", "Larus canus", 
                                                              "Uria lomvia", "Larus marinus", "Larus fuscus", "Cepphus grylle", 
                                                              "Arenaria interpres", "Haematopus ostralegus", "Alca torda", 
                                                              "Phalaropus lobatus", "Phalaropus fulicarius", "Anser albifrons flavirostris", 
                                                              "Tadorna tadorna", "Aythya marila", "Mareca strepera", "Anas acuta", 
                                                              "Anser anser", "Mergus merganser", "Anser brachyrhynchus", "Branta leucopsis", 
                                                              "Melanitta nigra", "Clangula hyemalis", "Bucephala islandica", 
                                                              "Branta bernicla", "Mareca penelope", "Spatula clypeata", "Aythya fuligula", 
                                                              "Anas platyrhynchos", "Histrionicus histrionicus", "Mergus serrator", 
                                                              "Anas crecca", "Cygnus cygnus", "Somateria spectabilis", "Somateria mollissima", 
                                                              "Columba livia", "Falco rusticolus", "Haliaeetus albicilla", 
                                                              "Falco columbarius", "Lagopus muta", "Acanthis flammea", "Spinus spinus", 
                                                              "Regulus regulus", "Passer domesticus", "Turdus pilaris", "Corvus corax", 
                                                              "Loxia curvirostra", "Motacilla alba", "Troglodytes troglodytes", 
                                                              "Turdus iliacus", "Plectrophenax nivalis", "Sturnus vulgaris", 
                                                              "Oenanthe oenanthe", "Turdus merula", "Anthus pratensis", "Phalacrocorax carbo", 
                                                              "Podiceps auritus", "Fulmarus glacialis", "Gavia immer", "Gavia stellata", 
                                                              "Hydrobates leucorhous", "Puffinus puffinus", "Hydrobates pelagicus", 
                                                              "Morus bassanus", "Phalacrocorax aristotelis", "Rallus aquaticus", 
                                                              "Asio flammeus", "Asio otus", "Bubo scandiacus")), row.names = c(NA, 
                                                                                                                               -93L), class = "data.frame")

fuglar <- as_tibble(fuglar) %>% arrange(isl_heiti)
```

## Fyrir töflu í feltbók
```{r cars}
data <- gogn %>% 
  mutate(tegund=str_to_sentence(tolower(tegund))) %>% 
  ddply(.(tegund,snid),summarise,N=table(tegund)) %>% 
  mutate(N=as.double(N))
knitr::kable(data,"markdown")

```

## Litlar myndir voru sóttar á phylopic.org eftir tilraunir með rphylopic (sjá skissur.R)

# Myndir

# Mynd 1:

```{r myndtalning}
data <- gogn %>% 
  mutate(tegund=str_to_sentence(tolower(tegund))) %>% 
  ddply(.(tegund),summarise,N=table(tegund)) %>% 
  mutate(N=as.double(N))
DF <- tibble(
  fjöldi = data$N,
  tegund = unique(data$tegund),
  image = list.files("./thumbs",full.names = T) %>% 
    as.list() %>%
    map(function(x) image_read(x))
  )

f1 = "Catamaran"
p <- ggplot(DF, aes(tegund, fjöldi, image = image)) +
  geom_isotype_col(
    img_height = grid::unit(1, "null"), img_width = NULL,
    ncol = 1, nrow = 1, hjust = 1, vjust = 0.5,
    colour = "#76653BFF"
  ) +
  coord_flip() +
  guides(fill = "none") +
  theme_classic(base_family = f1,
                base_size=80,
                base_line_size = .3,
                base_rect_size = 2)

png(here::here(paste0("talning", format(Sys.time(), "%Y%m%d_%H%M%S"), ".png")), res = 320, height = 9, width = 12, units = "in")
p
dev.off()

```


```{r myndfjarlaegd}
data <- gogn %>% mutate(tegund=str_to_sentence(tolower(tegund)),
                        fjarlaegd = fct_relevel(fjarlaegd,
                                                "0-25",
                                                "25-50",
                                                "50-100",
                                                "100+")) %>% 
  ddply(.(tegund,fjarlægð=fjarlaegd),summarise,fjöldi=table(tegund)) %>% 
  mutate(fjöldi=as.double(fjöldi))

p2 <- ggplot(data, aes(x=tegund, y=fjöldi, fill=fjarlægð)) +
  geom_bar(stat='identity', position='dodge') +
  theme_minimal(base_family = f1,
                base_size=80,
                base_line_size = .3,
                base_rect_size = 2) +
  coord_flip() +
  #theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  harrypotter::scale_fill_hp(discrete = TRUE, option = "ronweasley2", name = "fjarlægð") 

png(here::here(paste0("fjarlaegd", format(Sys.time(), "%Y%m%d_%H%M%S"), ".png")), res = 320, height = 9, width = 12, units = "in")
p2
dev.off()


```



